<<<<<<< HEAD
import Image from 'next/image';
import { useState, useContext } from 'react';
import { useTheme } from 'next-themes';
import BeatLoader from 'react-spinners/BeatLoader';

import images from '../assets';
import { Button, CurrencyField } from '../components';
import { DEFIContext } from '../context/DEFIContext';
import ConfigModal from '../components/ConfigModal';

const Home = () => {
  const { connectedAcc } = useContext(DEFIContext);
  const { theme, setTheme } = useTheme();
  const [activeSelect, setActiveSelect] = useState('DAI');
  const [showModal, setShowModal] = useState(false);
=======
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
>>>>>>> parent of 04323d1 (smart contracts 80% without faucet function and auto reward for staking, frontend without faucte page)

export default function Home() {
  return (
<<<<<<< HEAD
    <div className="flex flexCenter w-full sm:px-4 p-20 m-0 min-h-screen">
      <div className="w-2/4 border rounded-3xl p-6 mt-14 font-poppins bg-nft-black-1 dark:bg-nft-black-4">
        <div className="flex justify-between items-center mb-5">
          <h1 className="text-2xl font-bold text-white flexCenter">Swap</h1>
          <Image
            src={images.gear}
            objectFit="contain"
            width={35}
            height={35}
            alt="arrow"
            className="cursor-pointer"
            onClick={() => setShowModal((prev) => !prev)}
          />
        </div>
        <CurrencyField
          field="input"
          tokenName="WETH"
        />
        <CurrencyField
          field="output"
          tokenName="UNI"
        />
        <div className="flex-col flexCenter">
          <Button
            btnName="Swap"
            classStyle="uppercase rounded-2xl mt-4 w-full py-4 text-xl nft-gradient text-white"
          />
        </div>
      </div>

      {showModal && (
        <ConfigModal
          setShowModal={setShowModal}
        />
      )}
    </div>
  );
};

export default Home;
=======
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
>>>>>>> parent of 04323d1 (smart contracts 80% without faucet function and auto reward for staking, frontend without faucte page)
